
# policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/rsl_rl/Lite_flat/2025-10-30_19-36-44_kun_dance/exported/policy.onnx"
# motion_path: "{LEGGED_GYM_ROOT_DIR}/artifacts/kun_dance:v1/motion.npz"
policy_path: "{LEGGED_GYM_ROOT_DIR}/artifacts/lite_squat2_f0:v1/policy.onnx"
motion_path: "{LEGGED_GYM_ROOT_DIR}/artifacts/lite_squat2_f0:v1/motion.npz"
xml_path: "{LEGGED_GYM_ROOT_DIR}/source/whole_body_tracking/whole_body_tracking/assets/miniloong/xml/miniloong_fixed.xml"
urdf_path: "{LEGGED_GYM_ROOT_DIR}/source/whole_body_tracking/whole_body_tracking/assets/miniloong/urdf/miniloong_fixed.urdf"

IMU_NOISE: true
MOTOR_NOISE: true

# Total simulation time
simulation_duration: 1000
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

mujoco_to_policy_idx : [
    0, 2, 4, 6, 8, 10,
    1, 3, 5, 7, 9, 11,
]

kps: [
    # 左腿
    280, 240, 150, 280, 150, 150,
    # 右腿
    280, 240, 150, 280, 150, 150]

kds: [
    # 左腿
    14, 12, 10, 14, 10, 10,
    # 右腿 
    14, 12, 10, 14, 10, 10,]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
default_pos: [
    0.39, 0.0, -0.12, 0.74, 0.36, 0.0,
    0.39, 0.0, -0.12, 0.74, 0.36, 0.0]

action_scale: [
    # 左腿
    0.134, 0.0625, 0.25, 0.134, 0.1, 0.1,
    # 右腿
    0.134, 0.0625, 0.25, 0.134, 0.1, 0.1,]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
num_actions: 12
num_obs: 69

# ['left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint',
#  'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_roll_joint',
#  'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_pitch_joint',
#  'left_knee_joint', 'right_knee_joint',
#  'left_shoulder_pitch_joint','right_shoulder_pitch_joint',
#  'left_ankle_pitch_joint', 'right_ankle_pitch_joint',
#  'left_shoulder_roll_joint', 'right_shoulder_roll_joint',
#  'left_ankle_roll_joint', 'right_ankle_roll_joint',
#  'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint',
#  'left_elbow_joint', 'right_elbow_joint',
#  'left_wrist_roll_joint', 'right_wrist_roll_joint',
#  'left_wrist_pitch_joint', 'right_wrist_pitch_joint',
#  'left_wrist_yaw_joint', 'right_wrist_yaw_joint']

# +-----------------------------------------------------------+
# |Active Observation Terms in Group: 'policy' (shape: (160,))|
# +-----------+-----------------------------------+-----------+
# |   Index   | Name                              |   Shape   |
# +-----------+-----------------------------------+-----------+
# |     0     | command                           |   (24,)   |
# |     1     | motion_anchor_pos_b               |    (3,)   |
# |     2     | motion_anchor_ori_b               |    (6,)   |
# |     3     | base_lin_vel                      |    (3,)   |
# |     4     | base_ang_vel                      |    (3,)   |
# |     5     | joint_pos                         |   (12,)   |
# |     6     | joint_vel                         |   (12,)   |
# |     7     | actions                           |   (12,)   |
# +-----------+-----------------------------------+-----------+